# Generated by Django 2.0.3 on 2018-03-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField(max_length=200)),
                ('summary', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
